//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v12.1.1+6cdd561
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>İletişim Bilgisi</summary>
	[PublishedModel("docTypeContactInfo")]
	public partial class DocTypeContactInfo : PublishedElementModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		public new const string ModelTypeAlias = "docTypeContactInfo";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<DocTypeContactInfo, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public DocTypeContactInfo(IPublishedElement content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Adres Satırları
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactAddress")]
		public virtual global::System.Collections.Generic.IEnumerable<string> ContactAddress => this.Value<global::System.Collections.Generic.IEnumerable<string>>(_publishedValueFallback, "contactAddress");

		///<summary>
		/// Ülke Kodu: ISO 3166-1 alpha-2'ye göre 2 haneli ülke kodu
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactAddressCountry")]
		public virtual string ContactAddressCountry => this.Value<string>(_publishedValueFallback, "contactAddressCountry");

		///<summary>
		/// Ülke
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactAddressCountryNative")]
		public virtual string ContactAddressCountryNative => this.Value<string>(_publishedValueFallback, "contactAddressCountryNative");

		///<summary>
		/// İlçe
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactAddressCounty")]
		public virtual string ContactAddressCounty => this.Value<string>(_publishedValueFallback, "contactAddressCounty");

		///<summary>
		/// Semt
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactAddressDistrict")]
		public virtual string ContactAddressDistrict => this.Value<string>(_publishedValueFallback, "contactAddressDistrict");

		///<summary>
		/// İl
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactAddressLocality")]
		public virtual string ContactAddressLocality => this.Value<string>(_publishedValueFallback, "contactAddressLocality");

		///<summary>
		/// Eyalet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactAddressRegion")]
		public virtual string ContactAddressRegion => this.Value<string>(_publishedValueFallback, "contactAddressRegion");

		///<summary>
		/// İletişim Noktası Tanımı
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactDefinition")]
		public virtual string ContactDefinition => this.Value<string>(_publishedValueFallback, "contactDefinition");

		///<summary>
		/// E-Posta Adresleri
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactEmail")]
		public virtual global::System.Collections.Generic.IEnumerable<string> ContactEmail => this.Value<global::System.Collections.Generic.IEnumerable<string>>(_publishedValueFallback, "contactEmail");

		///<summary>
		/// Faks Numaraları
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactFax")]
		public virtual global::System.Collections.Generic.IEnumerable<string> ContactFax => this.Value<global::System.Collections.Generic.IEnumerable<string>>(_publishedValueFallback, "contactFax");

		///<summary>
		/// Harita Konumu - Enlem Değeri
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactGeoCoordinatesLatitude")]
		public virtual string ContactGeoCoordinatesLatitude => this.Value<string>(_publishedValueFallback, "contactGeoCoordinatesLatitude");

		///<summary>
		/// Harita Konumu - Boylam Değeri
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactGeoCoordinatesLongitude")]
		public virtual string ContactGeoCoordinatesLongitude => this.Value<string>(_publishedValueFallback, "contactGeoCoordinatesLongitude");

		///<summary>
		/// Harita Embed Kodu
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactLocationMap")]
		public virtual string ContactLocationMap => this.Value<string>(_publishedValueFallback, "contactLocationMap");

		///<summary>
		/// GSM
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactMobile")]
		public virtual global::System.Collections.Generic.IEnumerable<string> ContactMobile => this.Value<global::System.Collections.Generic.IEnumerable<string>>(_publishedValueFallback, "contactMobile");

		///<summary>
		/// Telefonlar
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactPhone")]
		public virtual global::System.Collections.Generic.IEnumerable<string> ContactPhone => this.Value<global::System.Collections.Generic.IEnumerable<string>>(_publishedValueFallback, "contactPhone");

		///<summary>
		/// Posta Kodu
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[ImplementPropertyType("contactPostalCode")]
		public virtual int ContactPostalCode => this.Value<int>(_publishedValueFallback, "contactPostalCode");

		///<summary>
		/// Web Sitesi Adresleri
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "12.1.1+6cdd561")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactWebsite")]
		public virtual global::System.Collections.Generic.IEnumerable<string> ContactWebsite => this.Value<global::System.Collections.Generic.IEnumerable<string>>(_publishedValueFallback, "contactWebsite");
	}
}
